Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/9/2023
var
idade: inteiro
Inicio

  Escreva("Digite sua idade:")
   Leia (idade)
        se (idade >= 18) entao
        escreva("Você é maior de idade!")
        senão
        se (idade < 18) entao
        escreva("Você é menor de idade!")

        fimse
        fimse
Fimalgoritmo